version: '3'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network-ibolo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER} 
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD} 
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    links:
      - mongodb
    networks:
      - mongo-network-ibolo

networks: 
    mongo-network-ibolo:
      driver: bridge

volumes:
  mongo-data:
    driver: local